<?php

/**
 * @file
 * Provides migration from backdrop sites.
 */

use Drupal\Core\Url;
use Drupal\Core\Database\DatabaseExceptionWrapper;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\migrate\Exception\RequirementsException;
use Drupal\migrate\MigrateExecutable;
use Drupal\migrate\Plugin\RequirementsInterface;

/**
 * Implements hook_help().
 (removed help for now)
 */


/**
 * Implements hook_migration_plugins_alter().

 If this is only applicable to D6 we can probably remove this function

 -- but we may just remove the IF statement at the beginning.
 */
function migrate_backdrop_migration_plugins_alter(&$definitions) {
  // This is why the deriver can't do this: the 'd6_taxonomy_vocabulary'
  // definition is not available to the deriver as it is running inside
  // getDefinitions().
  if (isset($definitions['d6_taxonomy_vocabulary'])) {
    $vocabulary_migration_definition = [
      'source' => [
        'ignore_map' => TRUE,
        'plugin' => 'd6_taxonomy_vocabulary',
      ],
      'destination' => [
        'plugin' => 'null',
      ],
      'idMap' => [
        'plugin' => 'null',
      ],
    ];
    $vocabulary_migration = \Drupal::service('plugin.manager.migration')->createStubMigration($vocabulary_migration_definition);

    try {
      $source_plugin = $vocabulary_migration->getSourcePlugin();
      if ($source_plugin instanceof RequirementsInterface) {
        $source_plugin->checkRequirements();
      }
      $executable = new MigrateExecutable($vocabulary_migration);
      $process = ['vid' => $definitions['d6_taxonomy_vocabulary']['process']['vid']];
      foreach ($source_plugin as $row) {
        $executable->processRow($row, $process);
        $source_vid = $row->getSourceProperty('vid');
        $plugin_ids = ['d6_term_node:' . $source_vid, 'd6_term_node_revision:' . $source_vid];
        foreach ($plugin_ids as $plugin_id) {
          // Match the field name derivation in d6_vocabulary_field.yml.
          $field_name = substr('field_' . $row->getDestinationProperty('vid'), 0, 32);

          // The Forum module is expecting 'taxonomy_forums' as the field name
          // for the forum nodes. The 'forum_vocabulary' source property is
          // evaluated in Drupal\taxonomy\Plugin\migrate\source\d6\Vocabulary
          // and is set to true if the vocabulary vid being migrated is the
          // same as the one in the 'forum_nav_vocabulary' variable on the
          // source site.
          $destination_vid = $row->getSourceProperty('forum_vocabulary') ? 'taxonomy_forums' : $field_name;
          $definitions[$plugin_id]['process'][$destination_vid] = 'tid';
        }
      }
    }
    catch (RequirementsException $e) {
      // This code currently runs whenever the definitions are being loaded and
      // if you have a Drupal 7 source site then the requirements will not be
      // met for the d6_taxonomy_vocabulary migration.
    }
    catch (DatabaseExceptionWrapper $e) {
      // When the definitions are loaded it is possible the tables will not
      // exist.
    }

  }
}
